### ISSUE TITLE
When no speller is available, falls back to SMS

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#164]
![DC9A68E1-CB77-4B80-AAFB-5C2FBE8F32F5](https://user-images.githubusercontent.com/1255285/83322204-58489a00-a25e-11ea-93d2-1d280b106830.jpeg)

In CRK yaml file, there is no speller specified:

```
targets:
  ios:
    legacyName: crk
  android:
    legacyName: crk
  win:
    locale: crk-Latn
    languageName: nēhiyawēwin
    legacyName: crk-win
```

To see this in action, install build 1590813586.
